version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: ecommerce-mysql
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_COLLATION: utf8mb4_unicode_ci

  java-app:
    image: maven:latest
    container_name: java-app
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    command: mvn clean install && mvn spring-boot:run
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db