version: '3.8'

services:
  app:
    image: openjdk:17-jdk-alpine
    container_name: java_app_container
    volumes:
      - ./target:/app
    working_dir: /app
    command: java -jar ecommerce-fitness-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/ecommerce_fitness
      - spring.jpa.hibernate.ddl-auto=none
      - spring.datasource.username=root
      - spring.datasource.password=${DB_PASSWORD}
      - api.security.token.secret=JWT_SCRET:secretKey

  mysql-db:
    image: mysql:latest
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: ecommerce-mysql
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_CHARSET: utf8
      MYSQL_COLLATION: utf8mb4_unicode_ci
